server:
  port: 0  # El puerto será asignado dinámicamente

spring:
  application:
    name: msvc-producto-pago  # Nombre del microservicio
  config:
    import: optional:configserver:http://config-server:8888  # Importar configuración desde el Config Server

